server:
  port: 9009

devuser:
  email: dev@karyeragame.com
  password: devpass

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    driver-class-name: org.postgresql.Driver
    username: testuser
    password:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG