server:
  port: 9009

devuser:
  email: dev@karyeragame.com
  password: devpass           # change to strong password and inject via env

email:
  from: careerA.game@gmail.com

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    driver-class-name: org.postgresql.Driver
    username: testuser
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls.enable: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG