CREATE TABLE IF NOT EXISTS Users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(20) NOT NULL,
        email varchar(100) NOT NULL,
        password varchar(100) NOT NULL,
        avatar varchar(255) NOT NULL,
        role varchar(15) NOT NULL,
        created_on timestamp NOT NULL,
        CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);