CREATE TABLE IF NOT EXISTS Avatars (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        url varchar(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(20) NOT NULL,
        email varchar(100) NOT NULL,
        password varchar(100) NOT NULL,
        avatar_id BIGINT,
        role varchar(15) NOT NULL,
        created_on timestamp NOT NULL,
        CONSTRAINT FK_USERS_ON_AVATARS FOREIGN KEY (avatar_id) REFERENCES Avatars (id),
        CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Games (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL,
        comment varchar(255),
        created_on timestamp NOT NULL,
        created_by BIGINT NOT NULL,
        status varchar(20) NOT NULL,
        start_balance int NOT NULL,
        CONSTRAINT FK_GAMES_ON_USERS FOREIGN KEY (created_by) REFERENCES Users (id)
);

CREATE TABLE IF NOT EXISTS Participants (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT,
        game_id BIGINT,
        PRIMARY KEY (user_id, game_id),
        CONSTRAINT FK_PARTICIPANTS_ON_USERS FOREIGN KEY (user_id) REFERENCES Users (id),
        CONSTRAINT FK_PARTICIPANTS_ON_GAMES FOREIGN KEY (game_id) REFERENCES Games (id)
);