spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls.enable: true

email:
  from: careerA.game@gmail.com