server:
  port: 9090

spring:
  data:
    rest:
      detection-strategy: annotated

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    driver-class-name: org.postgresql.Driver
    username: testuser
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9009
          jwk-set-uri: http://127.0.0.1:9009/oauth2/jwks

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls.enable: true

email:
  from: careerA.game@gmail.com

springdoc:
  api-docs:
    path=: /game-payment-service/v3/api-docs
  swagger-ui:
    oauth:
      clientId: gateway
      clientSecret: gateway-secret
  oAuthFlow:
    authorizationUrl: http://127.0.0.1:8080/oauth2/authorize
    tokenUrl: http://127.0.0.1:8080/oauth2/token